<?php

namespace Bmaker\Utils;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-06-01 at 12:29:08.
 */
class FileFinderTest extends \PHPUnit_Framework_TestCase
{

    public function testCaseSensitiveFind()
    {
        $ff = new FileFinder(__DIR__.'/*.php', true);
        $result = $ff->find(basename(__FILE__));
        $this->assertEquals(__FILE__, $result);
    }

    public function testCaseInsensitiveFind()
    {
        $ff = new FileFinder(__DIR__.'/*.php');
        $result = $ff->find(basename(__FILE__));
        $this->assertEquals(__FILE__, $result);
    }

    public function testNotFound()
    {
        $ff = new FileFinder(__DIR__.'/*.php');
        $result = $ff->find('not-found.txt');
        $this->assertNull($result);
    }
}
